# Generated by Django 5.2 on 2025-04-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='작가')),
                ('content', models.TextField(verbose_name='내용')),
                ('published_year', models.IntegerField(blank=True, null=True, verbose_name='발표 연도')),
                ('appreciation', models.TextField(blank=True, null=True, verbose_name='감상문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
