# Generated by Django 5.2 on 2025-04-28 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.RemoveField(
            model_name='poem',
            name='appreciation',
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='작성자명')),
                ('content', models.TextField(verbose_name='감상문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='poem.poem', verbose_name='시')),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='poems', to='poem.tag', verbose_name='태그'),
        ),
    ]
