# Generated by Django 5.2 on 2025-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='프로그램명')),
                ('program_type', models.CharField(max_length=100, verbose_name='유형')),
                ('target', models.CharField(max_length=100, verbose_name='대상')),
                ('duration', models.CharField(max_length=50, verbose_name='시간')),
                ('location', models.CharField(max_length=200, verbose_name='장소')),
                ('purpose', models.TextField(verbose_name='목적')),
                ('preparation', models.TextField(verbose_name='사전 준비물')),
                ('main_contents', models.TextField(verbose_name='주요 내용')),
                ('post_activity', models.TextField(verbose_name='사후 활동')),
                ('classification_criteria', models.CharField(max_length=100, verbose_name='분류 기준')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
